blogApp/config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  # namespace :api, defaults: {format: 'json'} do
  #   scope module: :v1, constraints: ApiConstraints.new(version: 1) do
  #     resources :posts
  #   end
  #   scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
  #     resources :posts
  #   end
  # end 
  namespace :api do
    namespace :v1 do
      resources :posts
      resources :authors
      resources :books
    end  
  end

  namespace :api do
    namespace :v2 do
      resources :posts
      resources :authors
      #resources :books
    end  
  end

  resources :books
  resources :authors do
    resources :posts
  	get "delete"
  end
  resources :posts do
  	get "delete"
    resources :comments do
    	get "delete"
    	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blogApp/app/models/book.rb
class Book
  include Mongoid::Document
  field :name, type: String
  field :one,  type: String
  field :two,  type: String
  field :three, type: String
  validates_presence_of :name
end

blogApp/app/controllers/api/v1/books_controller.rb
module Api
  module V1
    class BooksController < ApplicationController
      class Api::V1::BooksController < ApplicationController
        before_action :set_book, only: [:show, :update, :destroy]
        skip_before_action :verify_authenticity_token
        # GET /books
        def index
         @books = Book.all
         render json: @books
        end

        # GET /books/1
        def show
         render json: @book
        end
        # POST /books
        def create
         @book = Book.new(book_params)
         if @book.save
          render json: @book, status: :created, location:        api_v1_book_url(@book)
         else
          render json: @book.errors, status: :unprocessable_entity
         end
        end
        # PATCH/PUT /books/1
        def update
         if @book.update(book_params)
          render json: @book
         else
          render json: @book.errors, status: :unprocessable_entity
         end
        end
       # DELETE /books/1
        def destroy
         @book.destroy
        end
        private
        # Use callbacks to share common setup or constraints between actions.
        def set_book
         @book = Book.find(params[:id])
        end
        # Only allow a trusted parameter “white list” through.
        def book_params
        params.require(:book).permit(:name,:one,:two,:three)
        end
        end
    end
  end
end

blogApp/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name)
    end
end

blogApp/app/helpers/books_helper.rb
module BooksHelper
end

blogApp/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

blogApp/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

blogApp/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) , :id => "edit"  %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, :id => "destroy"   %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path , :id => "new_book" %>

blogApp/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

blogApp/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) , :id => "edit" %> |
<%= link_to 'Back', books_path , :id => "back" %>