blogApp/config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  # namespace :api, defaults: {format: 'json'} do
  #   scope module: :v1, constraints: ApiConstraints.new(version: 1) do
  #     resources :posts
  #   end
  #   scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
  #     resources :posts
  #   end
  # end 
  namespace :api do
    namespace :v1 do
      resources :posts
      resources :authors
      resources :books
    end  
  end

  namespace :api do
    namespace :v2 do
      resources :posts
      resources :authors
      #resources :books
    end  
  end

  resources :books
  resources :authors do
    resources :posts
  	get "delete"
  end
  resources :posts do
  	get "delete"
    resources :comments do
    	get "delete"
    	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blogApp/app/models/author.rb
class Author
  include Mongoid::Document
  field :name, type: String
  validates_presence_of :name
  has_many :posts
end

blogApp/app/controllers/api/v1/authors_controller.rb
module Api
  module V1
    class AuthorsController < ApplicationController
      class Api::V1::AuthorsController < ApplicationController
        before_action :set_author, only: [:show, :update, :destroy]
        skip_before_action :verify_authenticity_token
        # GET /authors
        def index
         @authors = Author.all
         render json: @authors
        end

        # GET /authors/1
        def show
         render json: @author
        end
        # POST /authors
        def create
         @author = Author.new(author_params)
         if @author.save
          render json: @author, status: :created, location:        api_v1_author_url(@author)
         else
          render json: @author.errors, status: :unprocessable_entity
         end
        end
        # PATCH/PUT /authors/1
        def update
         if @author.update(author_params)
          render json: @author
         else
          render json: @author.errors, status: :unprocessable_entity
         end
        end
       # DELETE /authors/1
        def destroy
         @author.destroy
        end
        private
        # Use callbacks to share common setup or constraints between actions.
        def set_author
         @author = Author.find(params[:id])
        end
        # Only allow a trusted parameter “white list” through.
        def author_params
        params.require(:author).permit(:name)
        end
        end
    end
  end
end

blogApp/app/controllers/api/v2/authors_controller.rb
module Api
    module V1
        class AuthorsController < ApplicationController
        end
    end
end

blogApp/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :all_authors, only: [:update, :create]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # POST /authors
  # POST /authors.json
  def create
    @authors = Author.all
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save!
         format.js { }
       # format.html { redirect_to @author, notice: 'Author was successfully created.' }
       # format.json { render :show, status: :created, location: @author }
      else
        format.js { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /authors/1/edit
  def edit
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
       format.js { } 
       # format.html { redirect_to @author, notice: 'Author was successfully updated.' }
       # format.json { render :show, status: :ok, location: @author }
      else
        format.js { render :edit }
        # format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  def delete
  @author = Author.find(params[:author_id])
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @posts = Post.where(author_id: @author.id).destroy_all
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    def all_authors
      @authors = Author.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

blogApp/app/helpers/authors_helper.rb
module AuthorsHelper
end

blogApp/app/views/authors/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Author</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @author.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Post", author_path(@author), method: :delete, remote: true, class: "btn btn-danger" ,:id => "delete" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

blogApp/app/views/authors/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @author, remote: true do |form| %>
      <div class="modal-body">   
        <div class="form-group">
          <%= form.label :name , class:"control-label"%>
          <%= form.text_field :name, class:"form-control" %>
        </div>
        
        <div class="actions">
          <%= form.submit 'Submit', :class => 'btn btn-success'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

blogApp/app/views/authors/_index.html.erb
 <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_author_path(author),remote: true ,class: "btn btn-primary" ,:id => "edit"  %></td>
        <td><%= link_to "Delete", author_delete_path(author), remote: true, class: "btn btn-danger" ,:id => "destroy"  %></td>
      </tr>
    <% end %>

blogApp/app/views/authors/create.js.erb
$(".author-index").html("<%= escape_javascript(render 'index') %>")
$("#author-modal").modal("hide")

blogApp/app/views/authors/delete.js.erb
$("#author-modal").html("<%= escape_javascript(render 'delete') %>")
$("#author-modal").modal("show")

blogApp/app/views/authors/destroy.js.erb
$("#author-modal").modal("hide")
$(".author-index").html("<%= escape_javascript(render 'index') %>")

blogApp/app/views/authors/edit.js.erb
$("#author-modal").html("<%= escape_javascript(render 'form') %>")
$("#author-modal").modal("show")

blogApp/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Authors</h1>
<div class="well">
  <%= link_to 'New Author', new_author_path , remote: true, class: "btn btn-default" ,:id => "new_author" %>
</div>
<div class="new-author"></div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Author Name</th>
      <th>View</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody class="author-index"> 
   <%= render 'index' %>
  </tbody>
</table>
<div id="author-modal" class="modal fade">
</div>

blogApp/app/views/authors/new.js.erb
$("#author-modal").html("<%= escape_javascript(render 'form') %>")
$("#author-modal").modal("show")

blogApp/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

blogApp/app/views/authors/update.js.erb
$(".author-index").html("<%= escape_javascript(render 'index') %>")
$("#author-modal").modal("hide")