newapp/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	resources :comments
  end
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

newapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

newapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

newapp/app/models/page.rb
class Page < ApplicationRecord
end

newapp/app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
end

newapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

newapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
	    redirect_to @post
	end
	def edit
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
	end
	def update
		@comment = Comment.find(params[:id])
		@comment.update(comment_params)
		redirect_to @post
	end
	def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
	end
	private 
	def comment_params 
		params.require(:comment).permit(:name ,:content)
	end
	private
	def set_post
		@post = Post.find(params[:post_id])	
	end
end

newapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@pages = Page.all
	end
	def show 
		@page = Page.find(params[:id])
		render text: params[:id]
	end
	def new
		@page = Page.new
	end
	def create 
		@page = Page.new(page_params) 
		@page.save
		redirect_to @page
	end
	def edit
		@page = Page.find(params[:id])		
	end
	def update
		@page = Page.find(params[:id])
		@page.update(page_params)
		redirect_to @page
	end

	def destroy
		@page = Page.find(params[:id])
		@page.destroy	
		redirect_to pages_path	
	end
	
	private 
	def page_params
		params.require(:page).permit(:title,:body,:slug)
    end



end
 

newapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title,:body)
    end
end

newapp/app/helpers/application_helper.rb
module ApplicationHelper
end

newapp/app/helpers/pages_helper.rb
module PagesHelper
end

newapp/app/helpers/posts_helper.rb
module PostsHelper
end

newapp/app/views/comments/_comment.html.erb
<div>
	<strong><%= comment.name %></strong>
	<strong><%= comment.content %></strong>
	<strong><%= @post.title %></strong>
	<div class="comment-admin">
  	<%= link_to "Edit", edit_post_comment_path(@post,comment) %> 
  	<%= link_to "Delete", [@post,comment],method: :delete %> 
	</div>
</div>

newapp/app/views/comments/_form.html.erb
<%= form_for [@post, comment] do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :content,"Comment" %>
		<%= f.text_area :content %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

newapp/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<h2><%= @post.title
 %><h2>
<%= render partial: "form",locals: {comment: @comment} %>

newapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

newapp/app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
<div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :body %>
	<%= f.text_field :body %>
</div>
<div class="field">
	<%= f.label :slug %>
	<%= f.text_field :slug %>
</div>
<p><%= f.submit %></p>
<% end %>

newapp/app/views/pages/create.html.erb
<%= Page.last %>

newapp/app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

newapp/app/views/pages/index.html.erb
<h1>Blog Pages</h1>

<% @pages.each do |page| %>
<p><%= link_to page.title, page %></p>
<% end %>

newapp/app/views/pages/new.html.erb
<%= render 'form', page: @page %>

newapp/app/views/pages/show.html.erb
 <h1><%= @page.title %></h1>
 <p><%= @page.body %>
 	<p><%= link_to "Edit", edit_page_path(@page) %></p>
 	<p><%= link_to "Delete", @page, method: :delete %></p>

newapp/app/views/posts/_comment.html.erb
<div>
	<strong><%= comment.name %></strong>
	<strong><%= comment.content %></strong>
</div>

newapp/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

newapp/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

newapp/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

newapp/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

newapp/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<div id="comments">
	<h1>Comments</h1>
	<h1>Post Check : <%= @post.title %></h1>
	 <%= render @post.comments %>
	 <h2>Add Comment</h2>
	 <%= render partial: "comments/form", locals: {comment: @post.comments.new} %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>